#!/bin/sh

set -e

case "$1" in
    remove|purge)
        if command -v udevadm >/dev/null 2>&1; then
            udevadm control --reload-rules >/dev/null 2>&1 || true
            udevadm trigger --action=change --sysname-match=uinput \
                >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
